import { useEffect, useRef } from 'react';
import {
  Box,
  VStack,
  HStack,
  Heading,
  Text,
  Badge,
  Button,
  SimpleGrid,
  Card,
  CardBody,
} from '@/shared/design-system';
import {
  SOURCE_BORDER,
  SOURCE_COLOR,
  SOURCE_LABEL,
  resolveGenerationSource,
  type LibraryQuizMeta,
  type QuizGenerationSource,
} from './quizLibraryStyles';

export interface QuizLibraryCardQuiz extends LibraryQuizMeta {
  id: string;
  name: string;
  description?: string;
  difficulty: string;
  grade_level?: string;
  subject?: string;
  number_of_questions: number;
  passing_percentage: number;
  time_limit?: number;
  created_at: string;
  created_by_name?: string | null;
  subtopics?: string[];
}

const DIFF_COLOR: Record<string, string> = {
  Basic: 'green',
  Easy: 'green',
  Medium: 'yellow',
  Intermediate: 'yellow',
  Hard: 'orange',
  Advanced: 'orange',
  Expert: 'red',
};

function formatQuizTitle(name: string): string {
  return name.replace(/^AI Quiz:\s*/i, '');
}

function formatGeneratedAt(iso: string): string {
  try {
    return new Date(iso).toLocaleString(undefined, {
      dateStyle: 'medium',
      timeStyle: 'short',
    });
  } catch {
    return '';
  }
}

interface QuizLibraryCardProps {
  quiz: QuizLibraryCardQuiz;
  isHighlighted?: boolean;
  isStarting?: boolean;
  onStart: (quiz: QuizLibraryCardQuiz) => void;
}

export const QuizLibraryCard: React.FC<QuizLibraryCardProps> = ({
  quiz,
  isHighlighted,
  isStarting,
  onStart,
}) => {
  const cardRef = useRef<HTMLDivElement>(null);
  const source: QuizGenerationSource = resolveGenerationSource(quiz);
  const borderColor = SOURCE_BORDER[source];
  const colorScheme = SOURCE_COLOR[source];

  useEffect(() => {
    if (isHighlighted && cardRef.current) {
      cardRef.current.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }, [isHighlighted]);

  return (
    <Card
      ref={cardRef}
      borderRadius="xl"
      boxShadow={isHighlighted ? 'lg' : 'sm'}
      borderWidth="1px"
      borderColor={isHighlighted ? 'yellow.400' : 'gray.100'}
      borderLeftWidth="4px"
      borderLeftColor={borderColor}
      outline={isHighlighted ? '2px solid' : undefined}
      outlineColor={isHighlighted ? 'yellow.300' : undefined}
      outlineOffset={isHighlighted ? '2px' : undefined}
      _hover={{ boxShadow: 'md' }}
      transition="box-shadow 0.15s, outline 0.15s"
    >
      <CardBody>
        <VStack align="stretch" spacing={3}>
          <HStack justify="space-between" align="start" flexWrap="wrap" gap={2}>
            <Badge colorScheme={colorScheme} borderRadius="full" fontSize="xs">
              {SOURCE_LABEL[source]}
            </Badge>
            {isHighlighted && (
              <Badge colorScheme="yellow" borderRadius="full" fontSize="xs">
                Just created
              </Badge>
            )}
          </HStack>

          <Box>
            <Heading size="sm" noOfLines={2} mb={1}>
              {formatQuizTitle(quiz.name)}
            </Heading>
            <Text fontSize="xs" color="gray.500" noOfLines={1}>
              {source === 'mine'
                ? 'Generated by you'
                : `Generated by ${quiz.created_by_name?.trim() || 'Unknown'}`}
              {quiz.created_at ? ` · ${formatGeneratedAt(quiz.created_at)}` : ''}
            </Text>
            {quiz.description && (
              <Text fontSize="xs" color="gray.500" noOfLines={2} mt={1}>
                {quiz.description}
              </Text>
            )}
          </Box>

          <HStack spacing={2} flexWrap="wrap">
            <Badge colorScheme={DIFF_COLOR[quiz.difficulty] || 'gray'} borderRadius="full" fontSize="xs">
              {quiz.difficulty}
            </Badge>
            {quiz.subject && (
              <Badge colorScheme="teal" borderRadius="full" fontSize="xs">
                {quiz.subject}
              </Badge>
            )}
            {quiz.grade_level && (
              <Badge colorScheme="cyan" borderRadius="full" fontSize="xs">
                {quiz.grade_level}
              </Badge>
            )}
            {(quiz.subtopics || []).map((st) => (
              <Badge key={st} colorScheme="purple" borderRadius="full" fontSize="xs" variant="subtle">
                {st}
              </Badge>
            ))}
          </HStack>

          <SimpleGrid columns={3} spacing={2} fontSize="xs" color="gray.600">
            <Box textAlign="center">
              <Text fontWeight="bold" fontSize="md">
                {quiz.number_of_questions}
              </Text>
              <Text>Questions</Text>
            </Box>
            <Box textAlign="center">
              <Text fontWeight="bold" fontSize="md">
                {quiz.passing_percentage}%
              </Text>
              <Text>Pass mark</Text>
            </Box>
            <Box textAlign="center">
              <Text fontWeight="bold" fontSize="md">
                {quiz.time_limit ? `${quiz.time_limit}m` : '∞'}
              </Text>
              <Text>Time</Text>
            </Box>
          </SimpleGrid>

          <Button
            colorScheme="blue"
            size="sm"
            borderRadius="xl"
            isLoading={isStarting}
            loadingText="Starting…"
            onClick={() => onStart(quiz)}
          >
            🚀 Start Quiz
          </Button>
        </VStack>
      </CardBody>
    </Card>
  );
};
