/** Paths for images generated by Ollama Cloud (quiz + study). */
const OLLAMA_IMAGE_UPLOAD_PREFIX = '/uploads/quiz-images/';

function isOllamaGeneratedImageUrl(url) {
  if (!url || typeof url !== 'string') return false;
  const trimmed = url.trim();
  return (
    trimmed.startsWith(OLLAMA_IMAGE_UPLOAD_PREFIX) ||
    trimmed.includes('/uploads/quiz-images/')
  );
}

function sanitizeOllamaImageUrl(url) {
  return isOllamaGeneratedImageUrl(url) ? String(url).trim() : null;
}

module.exports = {
  OLLAMA_IMAGE_UPLOAD_PREFIX,
  isOllamaGeneratedImageUrl,
  sanitizeOllamaImageUrl,
};
